🐄 Tabla: cattle (Vacuno)
Campos:
id (UUID)
crotal_number (string, único)
name (string)
iron_number (string)
breed (enum: morucha, charolesa, limousina, mixta)
sex (enum: hembra, macho)
birth_date (date)
deactivation_date (date, opcional)
location_id (relación → infrastructure)
father_id (relación → cattle, opcional)
mother_id (relación → cattle, opcional)
notes (texto, opcional)
created_at (timestamp)
updated_at (timestamp)